---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: BHOS-NVID
description: BlueHatOS w/ NVIDIA support
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

modules:
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (System)"
      install:
        - com.bitwarden.desktop
        - com.github.rafostar.Clapper
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - com.obsproject.Studio
        - com.rustdesk.RustDesk
        - com.valvesoftware.Steam.Utility.InhibitScreensaver
        - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
        - com.valvesoftware.Steam
        - com.visualstudio.code
        - io.github.alainm23.planify
        - io.github.flattool.Ignition
        - io.github.flattool.Warehouse
        - it.mijorus.gearlever
        - md.obsidian.Obsidian
        - org.ardour.Ardour
        - org.audacityteam.Audacity
        - org.blender.Blender
        - org.darktable.Darktable
        - org.gimp.GIMP
        - org.gimp.GIMP.Manual
        - org.gnome.baobab
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.font-viewer
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.NautilusPreviewer
        - org.gnome.Papers
        - org.gnome.TextEditor
        - org.inkscape.Inkscape
        - org.libreoffice.LibreOffice
        - org.mozilla.firefox
        - org.pipewire.Helvum
        - page.codeberg.libre_menu_editor.LibreMenuEditor

  - type: gnome-extensions
    install:
    - Alphabetical App Grid
    - AppIndicator and KStatusNotifierItem Support
    - Blur my Shell
    - Dash to Panel
    - GameMode Shell Extension
    - Gtk4 Desktop Icons NG (DING)
    - Tiling Shell

  - type: rpm-ostree
    repos:
    - https://copr.fedorainfracloud.org/coprs/jerrycasiano/FontManager/repo/fedora-40/jerrycasiano-FontManager-fedora-41.repo
    install:
    - fastfetch
    - font-manager
    remove:
    - firefox
    - firefox-langpacks
  
  - type: signing
