---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: BHOS-NVID
description: BlueHatOS w/ NVIDIA support
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 41

modules:
  - type: default-flatpaks
    notify: false
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (System)"
      install:
        - app.polychromatic.controller
        - com.heroicgameslauncher.hgl
        - com.obsproject.Studio
        - com.rustdesk.RustDesk
        - com.stremio.Stremio
        - com.todoist.Todoist
        - com.valvesoftware.Steam
        - com.valvesoftware.Steam.Utility.InhibitScreensaver
        - com.visualstudio.code
        - io.github.antimicrox.antimicrox
        - md.obsidian.Obsidian
        - net.davidotek.pupgui2
        - net.retrodeck.retrodeck
        - org.ardour.Ardour
        - org.audacityteam.Audacity
        - org.blender.Blender
        - org.darktable.Darktable
        - org.gimp.GIMP
        - org.inkscape.Inkscape
        - org.kde.gwenview
        - org.kde.kcalc
        - org.kde.kdenlive
        - org.kde.krita
        - org.kde.okular
        - org.kde.skanpage
        - org.libreoffice.LibreOffice
        - org.mozilla.firefox
        - org.mozilla.Thunderbird

  - type: rpm-ostree
    install:
    - fastfetch
    remove:
    - firefox
    - firefox-langpacks
  
  - type: signing
